Increase mkdoc version to 1.2.2.
python:alpine is now points to python3.10, with old mkdoc, it will reports:

```
from collections import Sequence, namedtuple
ImportError: cannot import name 'Sequence' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

This is due to:
> Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

Signed-off-by: atline <atline@aliyun.com>